### ISSUE TITLE
前端动画原理解析

### ISSUE THREAD

**Issue by LeeGenD** [LeeGenD/leegend.github.com#13]
# 前端动画原理与实现

@(技术积累)
### 概念

>  根据时间的变化，连续地改变元素的样式造成的动态效果
### 基本要素
-   动画时长：$T$
-   动画进程：$ p = \frac{t}{T}  $
-   缓动函数（easing）：$ e=f(p) $
-   元素样式函数：$ [attribute] = G(e) $
### 缓动函数

>  使运动看起来更加自然的函数

现实中由于各种因素，运动并不是单纯的直线，运动方向进行改变时也不是单纯的角度变换。所以，为了使运动看起来更自然，需要在运动时使用一些平缓的方式，由此便有了缓动函数。
#### 线性缓动函数

$ e=p $

```
function easing(p) {
    return p;
}
```

![Alt text](https://cloud.githubusercontent.com/assets/4611081/18273003/b9a43926-746d-11e6-82cd-8c73e1db3eb8.png)
#### 曲线缓动函数

$ e=p^4 $

```
function easing(p) {
    return Math.pow(p,4);
}
```

![Alt text](https://cloud.githubusercontent.com/assets/4611081/18273117/481d9fb2-746e-11e6-84e2-6213fd9aaaa4.png)
#### 正弦缓动函数

$ e=sin(\frac{\varPi}{2} \cdot p) $

```
function easing(p) {
    return Math.sin(0.5 * Math.PI * p);
}
```

![Alt text](https://cloud.githubusercontent.com/assets/4611081/18273140/6ac915aa-746e-11e6-9ebd-ab083e011ec4.png)
#### 贝塞尔曲线缓动函数

>  解释：一种只需要很少的控制点就能够生成复杂平滑曲线的方法
> （贝塞尔曲线扫盲 前端乱炖 http://www.html-js.com/article/1628）

下面我们就通过例子来了解一下如何用 de Casteljau 算法绘制一条贝塞尔曲线。
在平面内任选 3 个不共线的点，依次用线段连接。
![enter image description here](http://htmljs.b0.upaiyun.com/uploads/1386078245509-bezier-quadratic-start.png)

在第一条线段上任选一个点 D。计算该点到线段起点的距离 AD，与该线段总长 AB 的比例。
![enter image description here](http://htmljs.b0.upaiyun.com/uploads/1386078258661-bezier-quadratic-step1.png)

根据上一步得到的比例，从第二条线段上找出对应的点 E，使得 `AD:AB = BE:BC`。
![enter image description here](http://htmljs.b0.upaiyun.com/uploads/1386078272369-bezier-quadratic-step2.png)

连接这两点 DE。
![enter image description here](http://htmljs.b0.upaiyun.com/uploads/1386078284528-bezier-quadratic-step3.png)

从新的线段 DE 上再次找出相同比例的点 F，使得 `DF:DE = AD:AB = BE:BC`。
![enter image description here](http://htmljs.b0.upaiyun.com/uploads/1386078293828-bezier-quadratic-step4.png)

到这里，我们就确定了贝塞尔曲线上的一个点 F。接下来，请稍微回想一下中学所学的极限知识，让选取的点 D 在第一条线段上从起点 A 移动到终点 B，找出所有的贝塞尔曲线上的点 F。所有的点找出来之后，我们也得到了这条贝塞尔曲线。

![enter image description here](http://htmljs.b0.upaiyun.com/uploads/1386078307084-bezier-quadratic-end.png)

[动态绘制贝赛尔曲线](http://myst729.github.io/bezier-curve/)
#### 缓动函数例举

![Alt text](https://cloud.githubusercontent.com/assets/4611081/18274362/a4553e38-7474-11e6-94aa-969d9391e62e.png)
[缓动函数速查表](p)
##### 名词解释
-   easeIn：无初速度，逐渐开始加速
-   easeOut：有初速，逐渐减速到0
-   easeInOut：无初速度，逐渐开始加速后，逐渐开始减速到0
##### 缓动方程
-   Linear：线性 $p$
-   Quadratic：二次方 $p^2$
-   Cubic：三次方 $p^3$
-   Quartic：四次方 $p^4$
-   Quintic：五次方 $p^5$
-   Sinusoidal：正弦曲线 $sin(p)$
-   Exponential：指数曲线 $2^p$
-   Circular：圆形曲线的缓动 $\sqrt{1-p^2}$
-   Elastic：指数衰减的正弦曲线缓动
#### 基础位置移动

```
/*
* 以下例子中我们默认：
* 最大运动距离S为200px
* 缓动函数为线型缓动函数，即e=p
*/
var S = 200;
function easing(p) {
    return p;
}
```
##### 匀速运动

$ x=S \cdot p $

``` javascript
/**
* x=S*t/T
* 求导后 v=S/T 即速度恒定
*/
function animation(p) {
    return S * p;
}
```
##### 匀加速运动

$ x=S \cdot p^2 $

``` javascript
/**
* x=S*(t/T)^2
* 求导后 v=2S/(T^2)*t 即匀加速
*/
function animation(p) {
    return S * p * p;
}
```
##### 匀减速运动

$ x=S \cdot p \cdot (2-p) $

```
function animation(p) {
    return S * p * (2-p);
}
```
##### 简谐振动

$ x=S \cdot sin(2\varPi \cdot p) $ 

```
function animation(p) {
    return S * Math.sin(2 * Math.PI * p);
}
```
##### 斜线运动

$ x=S \cdot p $
$ y=S \cdot p $
##### 抛物线运动

$ x=S \cdot p $
$ y=S \cdot p^2 $
##### 正弦线

$ x=S \cdot p $
$ y=S \cdot sin(2\varPi \cdot p) $ 
##### 圆周运动

$ x=S \cdot cos(2\varPi \cdot p) $ 
$ y=S \cdot sin(2\varPi \cdot p) $ 
##### 动画角色介绍

![0](https://cloud.githubusercontent.com/assets/4611081/18128583/140fc3c6-6fb9-11e6-9157-a93579bc55b5.gif)

Kula

> 拳皇2000中出现的角色，操纵“反K艺术”，并使用“火”的反面“冰”
##### 示例代码

```
var imgList = ['./sprite/stand/1.png','./sprite/stand/2.png',...]
var listSize = imgList.length;
function animation(p) {
    var index = parseInt((listSize - 1)* p);
    return imgList[index];
}
```
#### 效果示例

[各种运动效果](https://leegend.github.io/animation-demo/demo.html)
##### setTimeout/setInterval

``` javascript
/**
 * @param {function} callback 需要延迟执行的函数
 * @param {number} time 延迟执行时间
 * @returns {number} 作为一个唯一的标识符.你可以将该值作为参数传给 window.clearTimeout() 来取消这个回调函数。
 */
function setTimeout(callback, time) {};
```

由于浏览器中js是单线程的，而setTimeout/setInterval只有在线程空闲的时候才会执行，所以延迟时间time并不准确
##### requestAnimationFrame

``` javascript
/**
 * @param {function} callback 需要执行的函数
 * @returns {number} 作为一个唯一的标识符.你可以将该值作为参数传给 window.cancelAnimationFrame() 来取消这个回调函数。
 */
function requestAnimationFrame(callback) {};
```
-   优化并行的动画动作，把能够合并的动作放在一个渲染周期内完成，如JS动画和CSS动画/变换或SVG SMIL动画，从而呈现出更流畅的动画效果。
-   页面最小化，或者被Tab切换了，将停止requestAnimationFrame，减少CPU，内存的压力`mark`
#### 动画对象封装

``` javascript
/**
* @description
* 动画对象
* @param {number} duration 运动时间
* @param {function} progress 运动函数
* @param {function} easing 缓动函数
*/
function Animation(duration, progress, easing) {
    this.duration = duration || 1000;
    this.progress = progress || function(e) {};
    this.easing = easing || function(p) {
        return p
    };
}
Animation.prototype = {
    start: function(callback) {
        var startTime = new Date();
        var _this = this;
        var runAnimation = function() {
            var p = (new Date() - startTime) / _this.duration;
            p = p > 1 ? 1 : p;
            var e = _this.easing(p);
            _this.progress(e);
            if (p == 1) {
                callback && callback();
            } else {
                window.requestAnimationFrame(runAnimation);
            }
        }
        runAnimation();
    }
}
```

``` javascript
// 匀速运动
new Animation(150, function(e) {
    var x = 200 * e;
    var y = 0;
    bullet.style.transform = 'translate(' + x + 'px,' + y + 'px)';
});
```

``` javascript
// 先旋转，然后匀速运动
var a1 = new Animation(1000, function(e) {
    ele.style.transform = 'rotate(' + 360 * e + 'deg)';
});
var a2 = new Animation(1000, function(e) {
    ele.style.transform = 'translate(' + 200 * e + 'px,0)';
});
a1.start(function() {
    a2.start();
});
```
#### 示例：子弹击出

[子弹击出](https://leegend.github.io/animation-demo/bullet-demo.html)
##### 属性讲解

``` css
/**
* transition-property: none | all | property;
* transition-duration: time;
* transition-timing-function: linear|ease|ease-in|ease-out|ease-in-out|cubic-bezier(n,n,n,n);
* transition-delay: time;
*/
#id {
    transition: property duration timing-function delay;
}
```
##### 示例

``` css
/* transition使用示例 */
.box {
    width: 50px;
    height: 50px;
    background-color: #ade;
    transition: all 2s;
    -moz-transition: all 2s;/* Firefox 4 */
    -webkit-transition: all 2s;/* Safari 和 Chrome */
    -o-transition: all 2s;/* Opera */
}

.box.active {
    width: 300px;
    background-color: #ead;
}
```

[css3 transition demo](https://leegend.github.io/animation-demo/css3-transition-demo.html)
##### 属性讲解

``` css
@keyframes animationname {keyframes-selector {css-styles;}}
```

| 值 | 描述 |
| :-- | :-: |
| animationname | 动画名称 |
| keyframes-selector | 动画帧的时长的百分比。 |
| css-styles | CSS 样式属性。 |

``` css
#id{
    animation: name duration timing-function delay iteration-count direction;
}
```

| 值 | 描述 |
| :-- | :-: |
| name | 动画名称 |
| duration | 动画时长 |
| timing-function | 速度曲线（`linear/ease/ease-in/其他`） |
| delay | 延迟时间 |
| iteration-count | 运行次数 (`n/infinite`) |
| direction | 方向（`normal/alternate`） |
##### 示例

``` css
/* keyframes使用示例 */
.box {
    animation: cleanTable 5s infinite;
}

@keyframes cleanTable {
    0% {
       top: 0px;
        background: #fff;
    }
    16.6% {
        top: 160px;
        background: #ccc;
    }
    33.3% {
        top: 30px;
        background: #999;
    }
    50% {
        top: 130px;
        background: #666;
    }
    66.6% {
        top: 60px;
        background: #333;
    }
    83.3% {
        top: 100px;
        background: #000;
    }
    100%{
        top: 0px;
        background: #fff;
    }
}
```

[css3 keyframes demo](https://leegend.github.io/animation-demo/css3-keyframes-demo.html)
##### will-change

告诉浏览器将要发生变化的属性是什么，并使用GPU来渲染变化

``` css
#id {
  transition: transform 0.3s;
}
#id:hover {
  will-change: transform;
}
#id:active {
  transform: scale(1);
}
```
##### webkitAnimationEnd

keyframes动画结束监听

``` javascript
dom.addEventListener('webkitAnimationEnd', function(){
  // 动画完成回调
});
```
### reflow与repaint
-   reflow：页面上元素的位置是联动的，当我们调解一个元素的大小或者坐标值，可能会触发其它元素位置的变化，称为回流或重排（reflow）
-   repaint：当元素的外观改变，如颜色、背景色等，需要重新绘制，称为重绘（repaint）
-   浏览器渲染过程
  1.  将dom分为多个图层
  2.  计算每个节点样式结果
  3.  生成节点图形和位置（reflow）
  4.  绘制节点样式到图层中（repaint）
  5.  生成最终图像（图层重组）
#### 尽量使用transform
-   tansform可以用来改变元素位置、大小、旋转等
-   tansform不会引发其它元素的reflow

[demo](https://leegend.github.io/animation-demo/performs-demo.html)
#### 尽量为js动画元素添加absolute、fixed的定位

[demo](https://leegend.github.io/animation-demo/performs-absolute-demo.html)
### 尽量使用CSS3动画
-   浏览器对CSS3动画进行优化
-   避免多余的JS逻辑代码
-   适用于简单动画
### 3D硬件加速
-   will-change
-   translate3d(0,0,0)

```
element.style:hover {
  will-change: transform;
}
```

```
element.style {
    transform: translate3d(-10px,-10px,0);
}
```
### 使用requestAnimationFrame
-   优化并行的动画动作，把能够合并的动作放在一个渲染周期内完成，如JS动画和CSS动画/变换或SVG SMIL动画，从而呈现出更流畅的动画效果。
-   页面最小化，或者被Tab切换了，将停止requestAnimationFrame，减少CPU，内存的压力
## 相关示例
-   [各种运动效果](https://leegend.github.io/animation-demo/demo.html)
-   [位置和帧动画结合：运动的Kula](https://leegend.github.io/animation-demo/kula.html)
-   [子弹击出](https://leegend.github.io/animation-demo/bullet-demo.html)
-   [延迟函数](https://leegend.github.io/animation-demo/delay-demo.html)
-   [CSS3 transition](https://leegend.github.io/animation-demo/css3-transition-demo.html)
-   [CSS3 keyframes](https://leegend.github.io/animation-demo/css3-keyframes-demo.html)
## 相关资料
-   [前端动画原理与实现](http://matrix.h5jun.com/slide/show?id=117#/)
-   [使用css3实现60帧动画](http://mp.weixin.qq.com/s?__biz=MzA4NjE3MDg4OQ==&mid=2650963599&idx=1&sn=bb28e6cf0e3146252313d22fe42cb885&scene=23&srcid=08292OL26qd1lpL3oZ8uNmJ1#rd)
-   [css vs js动画，谁最快](http://mp.weixin.qq.com/s?__biz=MzA4NjE3MDg4OQ==&mid=2650963527&idx=1&sn=c8d3f19a476781c733cb4e846759bca2&scene=23&srcid=0829LLRCMbP98JDRVaFRBEmn#rd)
-   [WAAPI入门](http://www.w3cplus.com/animation/waapi-basic-intro.html)
-   [a quick look into the math of animations of js](https://www.smashingmagazine.com/2011/10/quick-look-math-animations-javascript/)
