### ISSUE TITLE
大阴影的跳转型按钮的实现

### ISSUE THREAD

**Issue by LeeGenD** [LeeGenD/leegend.github.com#9]
# 问题描述

如果一个跳转型按钮的背景图阴影很大，比如：
html:

``` html
<a href="#" target="_blank"></a>
```

css:

``` css
a{
    position: absolute;
    background: url(normal.png);
}
a:hover{
    background: url(hover.png);
}
```

会导致点击到按钮阴影的时候就会产生跳转
![问题描述图片](http://leegend.github.io/images/img1.JPG)。
# 解决方法
- **div->a和javascript解决方案**

``` html
<div class="btn1">
    <a href="http://www.baidu.com" target="_blank" onmouseenter="this.parentNode.style.background='url(hover.png)'" onmouseleave="this.parentNode.style.background='normal.png'">
    </a>
</div>
```
- **a+div和css解决方案**

``` html
<div class="btn2">
    <a class="btn_hover" href="http://www.baidu.com" target="_blank"></a>
    <div class="btn_bg"></div>
</div>
```

``` css
.btn2 .btn_bg{
    width: 199px;
    height: 91px;
    background: url( ./img/a_big_shadow_btn.png);
    background-position: 0 -91px;
    position: absolute;
    top: 0;
}
.btn2 .btn_hover:hover + div{
    background-position: 0 -182px;
}
```
- [解决方案地址](http://leegend.github.io/example/a_big_shadow_btn.html)
